stages:
  - build
  - docker
  - release

build:maven:
  image: maven:3-adoptopenjdk-11
  stage: build
  tags:
    - build
  before_script:
    - apt update > /dev/null && apt install -y git > /dev/null
  script:
    - mvn clean package -Djasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}
  artifacts:
    expire_in: 120 mins
    name: $CI_JOB_NAME-$CI_COMMIT_REF_NAME
    paths:
      - target/telegrambot-0.0.1-SNAPSHOT.jar
      
package:docker:
  image: docker:stable
  stage: docker
  tags:
    - docker
  script:
    - docker build --build-arg JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD} -t telegram-bot:$CI_COMMIT_REF_NAME .
    - docker save telegram-bot:$CI_COMMIT_REF_NAME > telegram-bot.tar
  dependencies:
    - 'build:maven'
  artifacts:
    name: $CI_COMMIT_REF_NAME
    expire_in: 120 mins
    paths:
      - telegram-bot.tar

release:
  image: 'registry.gitlab.com/gitlab-org/release-cli:latest'
  stage: release
  needs:
    - job: 'build:maven'
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - release
  script:
    - echo 'running release_job'
  release:
    name: Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    description: Created using the release-cli